name: Deploy Backend

on:
  push:
    branches: [master]
    paths: ['backend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: backend
      - run: |
          # Delete failed stack if it exists
          aws cloudformation delete-stack --stack-name chimp-test-backend || true
          aws cloudformation wait stack-delete-complete --stack-name chimp-test-backend || true
        working-directory: backend
      - run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name chimp-test-backend \
            --parameter-overrides \
            SupabaseUrl=${{ secrets.SUPABASE_URL }} \
            SupabaseKey=${{ secrets.SUPABASE_KEY }}
        working-directory: backend