name: Deploy Backend

on:
  push:
    branches: [master]
    paths: ['backend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: backend
      - run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name chimp-test-backend \
            --parameter-overrides \
            SupabaseUrl=${{ secrets.SUPABASE_URL }} \
            SupabaseKey=${{ secrets.SUPABASE_KEY }}
        working-directory: backend
      - name: Cleanup old resources
        run: |
          # Get current stack resources
          CURRENT_FUNCTION=$(aws cloudformation describe-stack-resources --stack-name chimp-test-backend --query 'StackResources[?ResourceType==`AWS::Lambda::Function`].PhysicalResourceId' --output text)
          
          # Delete old Lambda functions not in current stack
          for func in $(aws lambda list-functions --query 'Functions[?starts_with(FunctionName, `chimp-test-backend-GameFunction`)].FunctionName' --output text); do
            if [ "$func" != "$CURRENT_FUNCTION" ]; then
              echo "Deleting old Lambda function: $func"
              aws lambda delete-function --function-name "$func" || true
            fi
          done
          
          # Delete old log groups
          for log_group in $(aws logs describe-log-groups --query 'logGroups[?contains(logGroupName, `chimp-test-backend-GameFunction`)].logGroupName' --output text); do
            if [[ "$log_group" != *"$CURRENT_FUNCTION"* ]]; then
              echo "Deleting old log group: $log_group"
              aws logs delete-log-group --log-group-name "$log_group" || true
            fi
          done